"""Regenerate portfolio/holdings.md and portfolio/portfolio-overview.md from
the classify-portfolio workflow's output JSON.

This script is the sole writer of those two generated pages. It never reads
DuckDB directly -- the classification JSON (already joined against holdings,
weights, and metadata) is the single input -- so runs are deterministic given
the same JSON. See references/page-contract.md for the exact page layouts.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[4]
sys.path.insert(0, str(ROOT / "src"))

import yaml  # noqa: E402

import kb_pages  # noqa: E402
from config import EXPORT_FOLDER, PORTFOLIO_GROUPING_FOLDER  # noqa: E402

DEFAULT_CLASSIFICATION = EXPORT_FOLDER / "portfolio-classification" / "portfolio-classification.json"
POLICY_FILE = PORTFOLIO_GROUPING_FOLDER / "policy_v1_1.yaml"


def load_classification(path: Path) -> dict:
    """Load the classification JSON, scoped to owned holdings only.

    `classify-portfolio` now classifies declared-wishlist tickers alongside
    owned holdings (`fields.ownership_status: "owned" | "wishlist"`, see
    `classify_portfolio`'s wishlist widening). This page renders *current
    holdings* -- a wishlist ticker has no position, weight, or market value,
    so it is filtered out here, once, rather than at every call site that
    reads `data["holdings"]`. `summary.holding_count`/`review_count` are
    recomputed against the filtered set for the same reason: `data["summary"]`
    as produced by `classify_portfolio()` counts owned + wishlist together.
    """
    data = json.loads(path.read_text(encoding="utf-8"))
    data["holdings"] = [
        h for h in data["holdings"] if h.get("fields", {}).get("ownership_status", "owned") == "owned"
    ]
    data["summary"] = {
        **data["summary"],
        "holding_count": len(data["holdings"]),
        "review_count": sum(1 for h in data["holdings"] if h.get("review_needed")),
        "classified_count": sum(1 for h in data["holdings"] if not h.get("review_needed")),
    }
    return data


def load_policy(path: Path) -> dict:
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def _num(value, fmt="{:,.2f}"):
    if value is None:
        return "—"
    try:
        return fmt.format(float(value))
    except (TypeError, ValueError):
        return str(value)


def _stock_link(ticker: str, stocks_dir: Path) -> str | None:
    page = stocks_dir / f"{ticker}.md"
    return f"stocks/{ticker}.md" if page.exists() else None


def render_holdings_page(data: dict, kb_root: Path, generated_at: str, today: str) -> str:
    stocks_dir = kb_root / "stocks"
    rows = []
    for holding in sorted(data["holdings"], key=lambda h: -(h["fields"].get("current_weight_percent") or 0)):
        fields = holding["fields"]
        ticker = holding["ticker"]
        link = _stock_link(ticker, stocks_dir)
        name_cell = f"[{holding['company_name']}](../{link})" if link else holding["company_name"]
        rows.append(
            "| {ticker} | {name} | {group} | {weight}% | {value} | {qty} | {yield_} | {confidence} |".format(
                ticker=ticker,
                name=name_cell,
                group=holding["primary_group"],
                weight=_num(fields.get("current_weight_percent")),
                value=_num(fields.get("position_market_value")),
                qty=_num(fields.get("quantity"), "{:,.4f}"),
                yield_=_num(fields.get("dividend_yield"), "{:.2f}"),
                confidence=holding["confidence"],
            )
        )
    review = [h["ticker"] for h in data["holdings"] if h.get("review_needed")]

    meta = {
        "title": "Holdings",
        "type": "portfolio-page",
        "tickers": sorted(h["ticker"] for h in data["holdings"]),
        "tags": ["holdings", "generated"],
        "status": "generated",
        "created": today,
        "updated": today,
        "summary": f"Current holdings synced from the classification workflow ({len(data['holdings'])} positions).",
        "related": ["portfolio-overview.md", "../taxonomy/index.md"],
        "generated_at": generated_at,
    }
    body_lines = [
        "\n# Holdings\n",
        "Generated by the `kb-sync-portfolio` skill from "
        "`exports/portfolio-classification/portfolio-classification.json`. Do not edit "
        "this page by hand -- re-run the skill instead.\n",
        "## Positions\n",
        "| Ticker | Company | Group | Weight | Market Value | Quantity | Yield % | Confidence |",
        "|---|---|---|---|---|---|---|---|",
        *rows,
        "",
    ]
    if review:
        body_lines += ["## Needs Review\n", ", ".join(review), ""]
    return kb_pages.serialize_page(meta, "\n".join(body_lines))


def render_overview_page(data: dict, policy: dict, generated_at: str, today: str) -> str:
    totals: dict[str, float] = {}
    for holding in data["holdings"]:
        group = holding["primary_group"]
        value = holding["fields"].get("position_market_value") or 0
        totals[group] = totals.get(group, 0) + float(value)
    total_value = sum(totals.values())

    targets = policy.get("allocation_targets", {})
    group_rows = []
    for group in policy.get("primary_groups", []):
        if group == "Needs Review":
            continue
        value = totals.get(group, 0.0)
        pct = (value / total_value * 100) if total_value else 0.0
        target = targets.get(group, {})
        group_rows.append(
            "| {group} | {pct:.1f}% | {target}% | {min_}% | {max_}% |".format(
                group=group,
                pct=pct,
                target=target.get("target_percent") if target.get("target_percent") is not None else "—",
                min_=target.get("min_percent") if target.get("min_percent") is not None else "—",
                max_=target.get("max_percent") if target.get("max_percent") is not None else "—",
            )
        )

    currency_totals: dict[str, float] = {}
    for holding in data["holdings"]:
        currency = holding["fields"].get("currency") or "Unknown"
        value = holding["fields"].get("position_market_value") or 0
        currency_totals[currency] = currency_totals.get(currency, 0) + float(value)
    currency_rows = [
        f"| {currency} | {_num(value)} | {_num(value / total_value * 100 if total_value else 0, '{:.1f}')}% |"
        for currency, value in sorted(currency_totals.items(), key=lambda item: -item[1])
    ]

    review = [h["ticker"] for h in data["holdings"] if h.get("review_needed")]
    summary = data["summary"]

    meta = {
        "title": "Portfolio Overview",
        "type": "portfolio-page",
        "tickers": [],
        "tags": ["overview", "generated"],
        "status": "generated",
        "created": today,
        "updated": today,
        "summary": (
            f"{summary['holding_count']} holdings, {summary['review_count']} needing review, "
            f"total market value {_num(total_value)}."
        ),
        "related": ["holdings.md", "allocation-policy.md", "../taxonomy/index.md"],
        "generated_at": generated_at,
    }
    body_lines = [
        "\n# Portfolio Overview\n",
        "Generated by the `kb-sync-portfolio` skill. Do not edit this page by hand -- "
        "re-run the skill instead.\n",
        f"- Holdings: {summary['holding_count']}",
        f"- Classified: {summary['classified_count']}",
        f"- Needs review: {summary['review_count']}",
        f"- Total market value: {_num(total_value)}\n",
        "## Group Allocation vs Policy\n",
        "| Group | Current % | Target % | Min % | Max % |",
        "|---|---|---|---|---|",
        *group_rows,
        "",
        "## Currency Split\n",
        "| Currency | Market Value | % of Portfolio |",
        "|---|---|---|",
        *currency_rows,
        "",
    ]
    if review:
        body_lines += ["## Needs Review\n", ", ".join(review), ""]
    return kb_pages.serialize_page(meta, "\n".join(body_lines))


def write_if_changed(path: Path, content: str, *, check: bool) -> bool:
    """Returns True if the file content differs from what's on disk."""
    existing = path.read_text(encoding="utf-8") if path.exists() else None
    changed = existing != content
    if changed and not check:
        path.write_text(content, encoding="utf-8", newline="\n")
    return changed


def main() -> int:
    parser = argparse.ArgumentParser(description="Sync generated portfolio pages from the classification JSON.")
    parser.add_argument("--classification", type=Path, default=DEFAULT_CLASSIFICATION)
    parser.add_argument("--check", action="store_true", help="Report whether pages would change; write nothing.")
    args = parser.parse_args()

    if not args.classification.exists():
        print(f"Classification file not found: {args.classification}", file=sys.stderr)
        return 1

    data = load_classification(args.classification)
    policy = load_policy(POLICY_FILE)

    kb_root = kb_pages.KB_ROOT
    today = kb_pages.today()
    # Date-only (not a timestamp) so re-running against unchanged input on the
    # same day is byte-identical -- required for `--check` to be meaningful.
    generated_at = today

    holdings_path = kb_root / "portfolio" / "holdings.md"
    overview_path = kb_root / "portfolio" / "portfolio-overview.md"

    holdings_content = render_holdings_page(data, kb_root, generated_at, today)
    overview_content = render_overview_page(data, policy, generated_at, today)

    holdings_changed = write_if_changed(holdings_path, holdings_content, check=args.check)
    overview_changed = write_if_changed(overview_path, overview_content, check=args.check)
    changed = holdings_changed or overview_changed

    if args.check:
        if changed:
            print("OUT OF DATE: holdings.md and/or portfolio-overview.md would change.")
            return 1
        print("UP TO DATE: no changes.")
        return 0

    index_path = kb_root / "portfolio" / "index.md"
    kb_pages.rebuild_index(index_path)
    kb_pages.rebuild_main_index(kb_root)

    if changed:
        kb_pages.append_update_log(
            kb_root,
            "synced",
            "portfolio/holdings.md, portfolio/portfolio-overview.md",
            f"Synced from {args.classification.name} ({data['summary']['holding_count']} holdings).",
            on=today,
        )
        print(f"Updated: {holdings_path}")
        print(f"Updated: {overview_path}")
    else:
        print("No changes (pages already up to date).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
