import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { StatTile } from "@/components/stat-tile";
import { WeightBars } from "@/components/charts/weight-bars";
import type { Concentration } from "@/lib/types";
import { fmtNumber, fmtPct } from "@/lib/format";

export function ConcentrationCard({ concentration }: { concentration: Concentration }) {
  const c = concentration;
  // Prefer the exemption-aware fields; fall back to the raw single-name
  // figures for reports generated by an older pipeline.
  const flaggedTicker = c.max_flagged_name_ticker ?? c.max_single_name_ticker;
  const flaggedWeight = c.max_flagged_name_weight ?? c.max_single_name_weight;
  const exempt = c.exempt_tickers ?? [];
  return (
    <Card>
      <CardHeader className="flex-row items-start justify-between gap-2">
        <div className="space-y-1.5">
          <CardTitle>Concentration</CardTitle>
          <CardDescription>How much of the portfolio rides on a few holdings</CardDescription>
        </div>
        {c.single_name_limit_breached ? (
          <Badge variant="destructive" className="font-normal">
            {flaggedTicker} {fmtPct(flaggedWeight)} — above the {fmtPct(c.single_name_limit)} single-name limit
          </Badge>
        ) : (
          <Badge variant="secondary" className="font-normal">Within single-name limit</Badge>
        )}
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="grid grid-cols-2 gap-2">
          <StatTile
            label="Effective holdings"
            value={c.effective_holdings != null ? `~${fmtNumber(c.effective_holdings, 1)}` : "—"}
            hint={`Spread-wise, the portfolio behaves like this many equal-sized holdings (1 / HHI; HHI = ${c.hhi?.toFixed(3) ?? "—"}). Fewer means more concentrated.`}
          />
          <StatTile
            label="Largest holding"
            value={fmtPct(c.max_single_name_weight)}
            hint={`${c.max_single_name_ticker} is the single biggest position.`}
          />
        </div>
        <WeightBars
          data={[
            { label: "Largest holding", weight: c.top_1 },
            { label: "5 largest holdings", weight: c.top_5 },
            { label: "10 largest holdings", weight: c.top_10 },
          ]}
          max={1}
        />
        <p className="text-muted-foreground text-xs">
          Policy caps any one holding at {fmtPct(c.single_name_limit)} of the portfolio
          {exempt.length
            ? `; broad-market core ETFs (${exempt.join(", ")}) are exempt because they are already diversified.`
            : "."}
        </p>
      </CardContent>
    </Card>
  );
}
